version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"  # port 8080
    volumes:
      - ./php/src:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/php.ini
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=app_database
      - POSTGRES_USER=my_user
      - POSTGRES_PASSWORD=my_password
    depends_on:
      - db

  db:
    image: postgres:17
    environment:
      - POSTGRES_DB=app_database
      - POSTGRES_USER=my_user
      - POSTGRES_PASSWORD=my_password
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./php/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5434:5432"

volumes:
  db_data: